# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

from typing import Mapping, Optional

from ._core import Core
from .resources import MeResource, OverviewResource, ObjectsResource, PlaygroundResource, EventsResource, SignalsResource, SettingsResource, WebhooksResource, WebhookDeliveriesResource, RulesResource, RuleFiringsResource, ApiKeysResource, BillingResource, UsageResource


class SigWise:
    """SigWise API client. Send events about your objects, get typed answers back.

    Example::

        sigwise = SigWise(api_key="your_key_id", secret="your_secret")
        sigwise.objects.get("user-42")

    Without arguments it reads SIGWISE_API_KEY, SIGWISE_SECRET and
    SIGWISE_BASE_URL from the environment.
    """

    me: MeResource
    overview: OverviewResource
    objects: ObjectsResource
    playground: PlaygroundResource
    events: EventsResource
    signals: SignalsResource
    settings: SettingsResource
    webhooks: WebhooksResource
    webhook_deliveries: WebhookDeliveriesResource
    rules: RulesResource
    rule_firings: RuleFiringsResource
    api_keys: ApiKeysResource
    billing: BillingResource
    usage: UsageResource

    def __init__(
        self,
        api_key: Optional[str] = None,
        secret: Optional[str] = None,
        *,
        base_url: Optional[str] = None,
        timeout: float = 30.0,
        max_retries: int = 2,
        headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        self._core = Core(api_key, secret, base_url=base_url, timeout=timeout, max_retries=max_retries, headers=headers)
        self.me = MeResource(self._core)
        self.overview = OverviewResource(self._core)
        self.objects = ObjectsResource(self._core)
        self.playground = PlaygroundResource(self._core)
        self.events = EventsResource(self._core)
        self.signals = SignalsResource(self._core)
        self.settings = SettingsResource(self._core)
        self.webhooks = WebhooksResource(self._core)
        self.webhook_deliveries = WebhookDeliveriesResource(self._core)
        self.rules = RulesResource(self._core)
        self.rule_firings = RuleFiringsResource(self._core)
        self.api_keys = ApiKeysResource(self._core)
        self.billing = BillingResource(self._core)
        self.usage = UsageResource(self._core)
