# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import os
import random
import secrets
import time
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Dict, Mapping, Optional

VERSION = "1.0.5"
DEFAULT_BASE_URL = "https://api.sigwise.ai"

# How long each request token is valid for, in seconds (the API allows 300).
TOKEN_TTL_SECONDS = 60

_RETRY_STATUSES = {408, 429, 500, 502, 503, 504}
_IDEMPOTENT = {"GET", "HEAD", "PUT", "DELETE", "OPTIONS"}


class SigWiseError(Exception):
    """The API answered with an error status."""

    def __init__(self, status: int, code: str, message: str, body: Any = None, headers: Optional[Mapping[str, str]] = None) -> None:
        super().__init__(message)
        #: The HTTP status code.
        self.status = status
        #: The machine-readable error code, e.g. ``not_found``.
        self.code = code
        self.message = message
        #: The decoded response body.
        self.body = body
        self.headers = dict(headers or {})

    def __str__(self) -> str:
        return f"{self.status} {self.code}: {self.message}"


class SigWiseConnectionError(Exception):
    """The request never got a response: a network error or a timeout."""


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def sign_request_token(api_key: str, secret: str, method: str, path: str, now: Optional[int] = None) -> str:
    """Sign the HS256 JWT that authenticates one request.

    ``kid`` names the key, ``iat``/``exp`` bound its lifetime, and
    ``htm``/``htu`` bind it to the method and path so it can't be replayed
    against another endpoint.
    """
    issued = int(time.time()) if now is None else now
    header = _b64url(json.dumps({"alg": "HS256", "typ": "JWT", "kid": api_key}, separators=(",", ":")).encode())
    claims: Dict[str, Any] = {
        "iat": issued,
        "exp": issued + TOKEN_TTL_SECONDS,
        "jti": secrets.token_hex(16),
        "htm": method.upper(),
    }
    # The server compares htu with the decoded path, so only bind paths it
    # can read back unchanged.
    if "?" not in path and "#" not in path:
        claims["htu"] = path
    payload = _b64url(json.dumps(claims, separators=(",", ":")).encode())
    signature = hmac.new(secret.encode(), f"{header}.{payload}".encode(), hashlib.sha256).digest()
    return f"{header}.{payload}.{_b64url(signature)}"


def _query_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if hasattr(value, "isoformat"):
        return str(value.isoformat())
    return str(value)


class Core:
    """The transport shared by every resource."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        secret: Optional[str] = None,
        *,
        base_url: Optional[str] = None,
        timeout: float = 30.0,
        max_retries: int = 2,
        headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        api_key = api_key or os.environ.get("SIGWISE_API_KEY")
        secret = secret or os.environ.get("SIGWISE_SECRET")
        if not api_key or not secret:
            raise ValueError(
                "SigWise: an API key and its secret are required. Pass api_key= and secret=, "
                "or set SIGWISE_API_KEY and SIGWISE_SECRET."
            )
        self.api_key = api_key
        self._secret = secret
        self.base_url = (base_url or os.environ.get("SIGWISE_BASE_URL") or DEFAULT_BASE_URL).rstrip("/")
        self.timeout = timeout
        self.max_retries = max_retries
        self.headers = dict(headers or {})

    def request(
        self,
        method: str,
        path: str,
        *,
        path_params: Optional[Mapping[str, str]] = None,
        query: Optional[Mapping[str, Any]] = None,
        body: Any = None,
        timeout: Optional[float] = None,
    ) -> Any:
        method = method.upper()
        raw_path = path
        encoded_path = path
        for name, value in (path_params or {}).items():
            if value is None or value == "":
                raise ValueError(f"SigWise: {name} is required")
            raw_path = raw_path.replace("{" + name + "}", str(value))
            encoded_path = encoded_path.replace("{" + name + "}", urllib.parse.quote(str(value), safe=""))

        params = [("api_key", self.api_key)]
        for key, value in (query or {}).items():
            if value is None:
                continue
            for v in value if isinstance(value, (list, tuple)) else [value]:
                params.append((key, _query_value(v)))
        url = self.base_url + encoded_path + "?" + urllib.parse.urlencode(params)
        data = None if body is None else json.dumps(body).encode()

        retries = self.max_retries if method in _IDEMPOTENT else 0
        attempt = 0
        while True:
            headers = {
                "Accept": "application/json",
                "User-Agent": f"sigwise-sdk/{VERSION} (python)",
                **self.headers,
                "Authorization": "Bearer " + sign_request_token(self.api_key, self._secret, method, raw_path),
            }
            if data is not None:
                headers["Content-Type"] = "application/json"
            req = urllib.request.Request(url, data=data, method=method, headers=headers)
            try:
                with urllib.request.urlopen(req, timeout=timeout or self.timeout) as resp:
                    return _decode(resp.status, resp.headers.get("Content-Type", ""), resp.read())
            except urllib.error.HTTPError as err:
                raw = err.read()
                if attempt < retries and err.code in _RETRY_STATUSES:
                    _sleep(attempt, err.headers.get("Retry-After"))
                    attempt += 1
                    continue
                decoded = _decode(err.code, err.headers.get("Content-Type", ""), raw)
                error = decoded.get("error", {}) if isinstance(decoded, dict) else {}
                raise SigWiseError(
                    err.code,
                    error.get("code") or f"http_{err.code}",
                    error.get("message") or f"{method} {raw_path} returned {err.code}",
                    decoded,
                    dict(err.headers.items()),
                ) from None
            except (urllib.error.URLError, TimeoutError, ConnectionError) as err:
                if attempt < retries:
                    _sleep(attempt, None)
                    attempt += 1
                    continue
                reason = getattr(err, "reason", err)
                raise SigWiseConnectionError(f"SigWise: {method} {raw_path} failed: {reason}") from err


def _decode(status: int, content_type: str, raw: bytes) -> Any:
    if status == 204 or not raw:
        return None
    if "json" in content_type:
        try:
            return json.loads(raw)
        except ValueError:
            pass
    return raw.decode("utf-8", "replace")


def _sleep(attempt: int, retry_after: Optional[str]) -> None:
    try:
        delay = min(float(retry_after), 60.0) if retry_after else -1.0
    except ValueError:
        delay = -1.0
    if delay < 0:
        base = min(0.5 * 2**attempt, 8.0)
        delay = base / 2 + random.random() * base / 2
    time.sleep(delay)
