# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

from __future__ import annotations

import hashlib
import hmac
import json
import time
from typing import Optional, Union

from . import types


class WebhookVerificationError(Exception):
    """The signature, timestamp or payload of a webhook delivery is not valid."""


def verify_webhook_signature(
    payload: Union[bytes, str],
    signature: Optional[str],
    timestamp: Optional[str],
    secret: str,
    *,
    tolerance: int = 300,
    now: Optional[int] = None,
) -> None:
    """Verify a webhook delivery.

    ``X-Webhook-Signature`` must be the HMAC-SHA256 of
    ``"<X-Webhook-Timestamp>.<raw body>"`` keyed with the endpoint secret, and
    the timestamp must be within ``tolerance`` seconds. Pass the raw body,
    exactly as received.
    """
    if not signature or not timestamp:
        raise WebhookVerificationError("missing signature or timestamp header")
    try:
        ts = int(timestamp)
    except ValueError:
        raise WebhookVerificationError("invalid timestamp") from None
    current = int(time.time()) if now is None else now
    if tolerance > 0 and abs(current - ts) > tolerance:
        raise WebhookVerificationError("timestamp outside the tolerance")
    body = payload.encode() if isinstance(payload, str) else payload
    mac = hmac.new(secret.encode(), timestamp.encode() + b"." + body, hashlib.sha256)
    if not hmac.compare_digest(("sha256=" + mac.hexdigest()).encode(), signature.encode()):
        raise WebhookVerificationError("signature mismatch")


def construct_webhook_event(
    payload: Union[bytes, str],
    signature: Optional[str],
    timestamp: Optional[str],
    secret: str,
    *,
    tolerance: int = 300,
    now: Optional[int] = None,
) -> types.WebhookEvent:
    """Verify a webhook delivery (see verify_webhook_signature) and parse its body."""
    verify_webhook_signature(payload, signature, timestamp, secret, tolerance=tolerance, now=now)
    try:
        return json.loads(payload)  # type: ignore[no-any-return]
    except ValueError:
        raise WebhookVerificationError("payload is not valid JSON") from None
