# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.

from typing import Any, Dict, List, Literal, Optional, Union, cast

from . import types
from ._core import Core

__all__ = [
    "MeResource",
    "OverviewResource",
    "ObjectsResource",
    "PlaygroundResource",
    "EventsResource",
    "SignalsResource",
    "SettingsResource",
    "WebhooksResource",
    "WebhookDeliveriesResource",
    "RulesResource",
    "RuleFiringsResource",
    "ApiKeysResource",
    "BillingResource",
    "UsageResource",
]


class MeResource:
    """The authenticated principal and tenant settings."""

    def __init__(self, core: Core) -> None:
        self._core = core

    def get(self, *, timeout: Optional[float] = None) -> types.Me:
        """Get the current principal.

        Returns the tenant the credential belongs to. For console tokens it also returns
        the signed-in user and whether they finished onboarding.

        ``GET /v1/me``
        """
        return cast(
            "types.Me",
            self._core.request(
                "GET",
                "/v1/me",
                timeout=timeout,
            ),
        )


class OverviewResource:
    """An object is anything you want answers about: a user, a listing, an order."""

    def __init__(self, core: Core) -> None:
        self._core = core

    def get(self, *, timeout: Optional[float] = None) -> types.Overview:
        """Get tenant overview.

        Tenant-wide totals and per-signal value distributions, computed with SQL
        aggregates.

        ``GET /v1/overview``
        """
        return cast(
            "types.Overview",
            self._core.request(
                "GET",
                "/v1/overview",
                timeout=timeout,
            ),
        )


class ObjectsResource:
    """An object is anything you want answers about: a user, a listing, an order."""

    def __init__(self, core: Core) -> None:
        self._core = core

    def analyze_all(self, *, timeout: Optional[float] = None) -> types.AnalyzeAllScheduled:
        """Re-analyze every object.

        Schedules a re-analysis of every object the tenant has, typically after changing
        signal configuration. Jobs run at bulk priority, behind live traffic. Each
        analysis is billed.

        ``POST /v1/analyze``
        """
        return cast(
            "types.AnalyzeAllScheduled",
            self._core.request(
                "POST",
                "/v1/analyze",
                timeout=timeout,
            ),
        )

    def list(
        self,
        *,
        q: Optional[str] = None,
        sort: Optional[Literal["recent",
        "flagged",
        "trust"]] = None,
        limit: Optional[int] = None,
        offset: Optional[int] = None,
        cursor: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> types.ObjectList:
        """List objects.

        Returns one page of objects with their latest analysis.

        `q` is either a substring of the object ID or display name, or a signal query
        such as `is_scammer > 90 and trust_score < 1` (see [Search and
        conditions](https://sigwise.ai/docs/guides/queries)).

        ``GET /v1/objects``
        """
        return cast(
            "types.ObjectList",
            self._core.request(
                "GET",
                "/v1/objects",
                query={"q": q, "sort": sort, "limit": limit, "offset": offset, "cursor": cursor},
                timeout=timeout,
            ),
        )

    def get(self, object_id: str, *, timeout: Optional[float] = None) -> types.ObjectAnalysis:
        """Get an object's analysis.

        Returns the latest answer for each signal computed for the object, plus the
        configured signals that have no answer yet (`pending`).

        Reads are cached for a few seconds; the `X-Cache` header says whether this one
        was a `HIT` or a `MISS`. Ingesting events and completed analyses invalidate the
        cache.

        ``GET /v1/objects/{object_id}``
        """
        return cast(
            "types.ObjectAnalysis",
            self._core.request(
                "GET",
                "/v1/objects/{object_id}",
                path_params={"object_id": object_id},
                timeout=timeout,
            ),
        )

    def get_state(self, object_id: str, *, timeout: Optional[float] = None) -> types.ObjectState:
        """Get an object's compacted history.

        Older events are folded into a rolling summary so the analyzer gets a bounded
        payload while keeping long-term signal. This returns that summary and the
        compaction cursor.

        ``GET /v1/objects/{object_id}/state``
        """
        return cast(
            "types.ObjectState",
            self._core.request(
                "GET",
                "/v1/objects/{object_id}/state",
                path_params={"object_id": object_id},
                timeout=timeout,
            ),
        )

    def analyze(
        self,
        object_id: str,
        *,
        timeout: Optional[float] = None,
    ) -> types.AnalyzeScheduled:
        """Re-analyze an object.

        Schedules an immediate re-analysis without a new event, for example right after
        adding a signal. Runs at live priority; poll `GET /v1/objects/{object_id}` for
        the result. Returns `404` when the object has no events.

        ``POST /v1/objects/{object_id}/analyze``
        """
        return cast(
            "types.AnalyzeScheduled",
            self._core.request(
                "POST",
                "/v1/objects/{object_id}/analyze",
                path_params={"object_id": object_id},
                timeout=timeout,
            ),
        )


class PlaygroundResource:
    """Events and messages are the evidence an object's answers are computed from."""

    def __init__(self, core: Core) -> None:
        self._core = core

    def run(
        self,
        *,
        events: List[types.EventInput],
        object_type: Optional[str] = None,
        signals: Optional[List[str]] = None,
        timeout: Optional[float] = None,
    ) -> types.PlaygroundResult:
        """Try signals on sample events.

        Scores sample events against your enabled signals and returns the answers,
        **without recording anything**: no object is created, the events and answers are
        not stored, and no rule or webhook fires. Use it to check how your signals judge
        content before you send real traffic, or after you change a signal's
        instructions.

        The events are scored on their own, with no history. Restrict the run to some
        signals with `signals`. At most 50 events per run.

        The analysis is real, so it is charged to your balance like any other and
        counted as a synchronous analysis in your usage. Returns `402` when the balance
        is empty, `429` when the account already has the maximum number of synchronous
        analyses in flight, and `503` with `analyzer_busy` when the analyzer is
        throttling.

        ``POST /v1/playground``
        """
        body: Dict[str, Any] = {}
        body["events"] = events
        if object_type is not None:
            body["object_type"] = object_type
        if signals is not None:
            body["signals"] = signals
        return cast(
            "types.PlaygroundResult",
            self._core.request(
                "POST",
                "/v1/playground",
                body=body,
                timeout=timeout,
            ),
        )


class EventsResource:
    """Events and messages are the evidence an object's answers are computed from."""

    def __init__(self, core: Core) -> None:
        self._core = core

    def ingest(
        self,
        object_id: str,
        *,
        events: List[types.EventInput],
        object_type: Optional[str] = None,
        wait: Optional[bool] = None,
        signals: Optional[List[str]] = None,
        include_history: Optional[bool] = None,
        timeout: Optional[float] = None,
    ) -> Union[types.ModerationVerdict, types.IngestAccepted]:
        """Ingest events.

        Records one or more events or messages about an object.

        **Asynchronous (default).** Returns `202` immediately and schedules a debounced
        analysis: a burst of events for one object coalesces into a single analysis once
        activity settles. Read the answers with `GET /v1/objects/{object_id}` or receive
        them by webhook.

        **Synchronous (`wait: true`).** Blocks on the analyzer and returns the verdict
        inline with `200`, so you can approve, review or block content before publishing
        it. Restrict scoring to some signals with `signals`, and score the request's
        events in isolation with `include_history: false`.

        Returns `402` when the tenant's balance is empty. A synchronous request returns
        `429` when the account already has the maximum number of synchronous analyses in
        flight (8 by default), and `503` with `analyzer_busy` when the analyzer is
        throttling; the events are recorded either way, so don't resend them: after
        `Retry-After`, request an analysis with `POST /v1/objects/{object_id}/analyze`
        and read the answers with `GET /v1/objects/{object_id}` or by webhook.

        **Safe retries.** Send an `Idempotency-Key` header (any unique string, such as a
        UUID) and retry with the same key after a timeout or a `5xx`: the events are
        recorded once. A repeat of an asynchronous request is answered like the first
        and carries `Idempotent-Replayed: true`. A repeat of a synchronous request
        returns `409` without analyzing (or charging) again; read the verdict with `GET
        /v1/objects/{object_id}`. Reusing a key for a different object returns `422`.
        Keys are remembered for 24 hours.

        ``POST /v1/objects/{object_id}/events``
        """
        body: Dict[str, Any] = {}
        body["events"] = events
        if object_type is not None:
            body["object_type"] = object_type
        if wait is not None:
            body["wait"] = wait
        if signals is not None:
            body["signals"] = signals
        if include_history is not None:
            body["include_history"] = include_history
        return cast(
            "Union[types.ModerationVerdict, types.IngestAccepted]",
            self._core.request(
                "POST",
                "/v1/objects/{object_id}/events",
                path_params={"object_id": object_id},
                body=body,
                timeout=timeout,
            ),
        )

    def list(self, object_id: str, *, timeout: Optional[float] = None) -> types.EventList:
        """List an object's events.

        Returns up to the 200 most recent events and messages recorded for the object,
        newest first.

        ``GET /v1/objects/{object_id}/events``
        """
        return cast(
            "types.EventList",
            self._core.request(
                "GET",
                "/v1/objects/{object_id}/events",
                path_params={"object_id": object_id},
                timeout=timeout,
            ),
        )


class SignalsResource:
    """A signal is a question you ask about every object, such as "is this a scammer?"
    (`noul`), "how trustworthy is this user?" (`score`) or "what is their buyer
    intent?" (`choice`).
    """

    def __init__(self, core: Core) -> None:
        self._core = core

    def list(self, *, timeout: Optional[float] = None) -> types.SignalList:
        """List signals.

        ``GET /v1/signals``
        """
        return cast(
            "types.SignalList",
            self._core.request(
                "GET",
                "/v1/signals",
                timeout=timeout,
            ),
        )

    def upsert(
        self,
        key: str,
        *,
        type: types.SignalType,
        instructions: Any,
        criteria: Any = None,
        enabled: Optional[bool] = None,
        timeout: Optional[float] = None,
    ) -> types.Signal:
        """Create or update a signal.

        Creates the signal, or replaces its definition. `instructions` and `criteria`
        are passed to the analyzer verbatim; the shape of `criteria` depends on `type`:

        | `type` | `criteria` |
        |----------|------------------------------------------------------|
        | `noul` | object with optional `true` / `false` descriptions |
        | `score` | ordered array of level descriptions, low to high |
        | `choice` | object mapping each option to a description or null |

        Creating a signal does not analyze existing objects unless the tenant setting
        `auto_backfill_signals` is on; start a backfill explicitly with `POST
        /v1/signals/{key}/backfill`.

        ``PUT /v1/signals/{key}``
        """
        body: Dict[str, Any] = {}
        body["type"] = type
        body["instructions"] = instructions
        if criteria is not None:
            body["criteria"] = criteria
        if enabled is not None:
            body["enabled"] = enabled
        return cast(
            "types.Signal",
            self._core.request(
                "PUT",
                "/v1/signals/{key}",
                path_params={"key": key},
                body=body,
                timeout=timeout,
            ),
        )

    def delete(self, key: str, *, timeout: Optional[float] = None) -> None:
        """Delete a signal.

        ``DELETE /v1/signals/{key}``
        """
        self._core.request(
            "DELETE",
            "/v1/signals/{key}",
            path_params={"key": key},
            timeout=timeout,
        )

    def get_backfill(self, key: str, *, timeout: Optional[float] = None) -> types.BackfillStatus:
        """Get backfill estimate and progress.

        Returns how many existing objects have no answer for the signal and what
        analyzing them would cost now, plus the progress of the most recent backfill
        (`null` if none was started).

        ``GET /v1/signals/{key}/backfill``
        """
        return cast(
            "types.BackfillStatus",
            self._core.request(
                "GET",
                "/v1/signals/{key}/backfill",
                path_params={"key": key},
                timeout=timeout,
            ),
        )

    def start_backfill(self, key: str, *, timeout: Optional[float] = None) -> types.SignalBackfill:
        """Start a backfill.

        Re-analyzes, for this signal only, every existing object that has no answer for
        it. Jobs run at bulk priority so they never delay live ingest. Each analysis is
        billed. Returns `409` if the signal is disabled.

        ``POST /v1/signals/{key}/backfill``
        """
        return cast(
            "types.SignalBackfill",
            self._core.request(
                "POST",
                "/v1/signals/{key}/backfill",
                path_params={"key": key},
                timeout=timeout,
            ),
        )


class SettingsResource:
    """The authenticated principal and tenant settings."""

    def __init__(self, core: Core) -> None:
        self._core = core

    def get(self, *, timeout: Optional[float] = None) -> types.Settings:
        """Get tenant settings.

        ``GET /v1/settings``
        """
        return cast(
            "types.Settings",
            self._core.request(
                "GET",
                "/v1/settings",
                timeout=timeout,
            ),
        )

    def update(
        self,
        *,
        auto_backfill_signals: Optional[bool] = None,
        timeout: Optional[float] = None,
    ) -> types.Settings:
        """Update tenant settings.

        Omitted fields are left unchanged.

        ``PATCH /v1/settings``
        """
        body: Dict[str, Any] = {}
        if auto_backfill_signals is not None:
            body["auto_backfill_signals"] = auto_backfill_signals
        return cast(
            "types.Settings",
            self._core.request(
                "PATCH",
                "/v1/settings",
                body=body,
                timeout=timeout,
            ),
        )


class WebhooksResource:
    """Webhook endpoints receive a signed `POST` for the event types they subscribe to:
    `analysis.completed` each time an analysis completes, and `rule.triggered` when
    a rule with a webhook action fires.
    """

    def __init__(self, core: Core) -> None:
        self._core = core

    def list(self, *, timeout: Optional[float] = None) -> types.WebhookEndpointList:
        """List webhook endpoints.

        ``GET /v1/webhooks``
        """
        return cast(
            "types.WebhookEndpointList",
            self._core.request(
                "GET",
                "/v1/webhooks",
                timeout=timeout,
            ),
        )

    def create(
        self,
        *,
        url: str,
        description: Optional[str] = None,
        signal_keys: Optional[List[str]] = None,
        events: Optional[List[types.WebhookEventType]] = None,
        enabled: Optional[bool] = None,
        timeout: Optional[float] = None,
    ) -> types.WebhookEndpointCreated:
        """Register a webhook endpoint.

        Registers an endpoint and returns its signing secret. **The secret is shown only
        once**; store it to verify deliveries.

        ``POST /v1/webhooks``
        """
        body: Dict[str, Any] = {}
        body["url"] = url
        if description is not None:
            body["description"] = description
        if signal_keys is not None:
            body["signal_keys"] = signal_keys
        if events is not None:
            body["events"] = events
        if enabled is not None:
            body["enabled"] = enabled
        return cast(
            "types.WebhookEndpointCreated",
            self._core.request(
                "POST",
                "/v1/webhooks",
                body=body,
                timeout=timeout,
            ),
        )

    def get(self, endpoint_id: str, *, timeout: Optional[float] = None) -> types.WebhookEndpoint:
        """Get a webhook endpoint.

        ``GET /v1/webhooks/{endpoint_id}``
        """
        return cast(
            "types.WebhookEndpoint",
            self._core.request(
                "GET",
                "/v1/webhooks/{endpoint_id}",
                path_params={"endpoint_id": endpoint_id},
                timeout=timeout,
            ),
        )

    def update(
        self,
        endpoint_id: str,
        *,
        url: Optional[str] = None,
        description: Optional[str] = None,
        signal_keys: Optional[List[str]] = None,
        events: Optional[List[types.WebhookEventType]] = None,
        enabled: Optional[bool] = None,
        timeout: Optional[float] = None,
    ) -> types.WebhookEndpoint:
        """Update a webhook endpoint.

        Omitted fields are left unchanged.

        ``PATCH /v1/webhooks/{endpoint_id}``
        """
        body: Dict[str, Any] = {}
        if url is not None:
            body["url"] = url
        if description is not None:
            body["description"] = description
        if signal_keys is not None:
            body["signal_keys"] = signal_keys
        if events is not None:
            body["events"] = events
        if enabled is not None:
            body["enabled"] = enabled
        return cast(
            "types.WebhookEndpoint",
            self._core.request(
                "PATCH",
                "/v1/webhooks/{endpoint_id}",
                path_params={"endpoint_id": endpoint_id},
                body=body,
                timeout=timeout,
            ),
        )

    def delete(self, endpoint_id: str, *, timeout: Optional[float] = None) -> None:
        """Delete a webhook endpoint.

        Removes the endpoint and its deliveries.

        ``DELETE /v1/webhooks/{endpoint_id}``
        """
        self._core.request(
            "DELETE",
            "/v1/webhooks/{endpoint_id}",
            path_params={"endpoint_id": endpoint_id},
            timeout=timeout,
        )


class WebhookDeliveriesResource:
    """Webhook endpoints receive a signed `POST` for the event types they subscribe to:
    `analysis.completed` each time an analysis completes, and `rule.triggered` when
    a rule with a webhook action fires.
    """

    def __init__(self, core: Core) -> None:
        self._core = core

    def list(
        self,
        *,
        status: Optional[types.DeliveryStatus] = None,
        endpoint_id: Optional[str] = None,
        limit: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> types.WebhookDeliveryList:
        """List webhook deliveries.

        Recent deliveries, newest first. Filter with `status=dead` to inspect the
        dead-letter queue.

        ``GET /v1/webhook_deliveries``
        """
        return cast(
            "types.WebhookDeliveryList",
            self._core.request(
                "GET",
                "/v1/webhook_deliveries",
                query={"status": status, "endpoint_id": endpoint_id, "limit": limit},
                timeout=timeout,
            ),
        )

    def replay(
        self,
        delivery_id: str,
        *,
        timeout: Optional[float] = None,
    ) -> types.WebhookDelivery:
        """Replay a delivery.

        Re-queues a delivery (for example one in the dead-letter queue) for another
        attempt.

        ``POST /v1/webhook_deliveries/{delivery_id}/replay``
        """
        return cast(
            "types.WebhookDelivery",
            self._core.request(
                "POST",
                "/v1/webhook_deliveries/{delivery_id}/replay",
                path_params={"delivery_id": delivery_id},
                timeout=timeout,
            ),
        )


class RulesResource:
    """A rule fires an action (email, Slack or webhook) when an object's signal values
    cross a line you care about, such as `is_scammer >= 90`.
    """

    def __init__(self, core: Core) -> None:
        self._core = core

    def list(self, *, timeout: Optional[float] = None) -> types.RuleList:
        """List rules.

        ``GET /v1/rules``
        """
        return cast(
            "types.RuleList",
            self._core.request(
                "GET",
                "/v1/rules",
                timeout=timeout,
            ),
        )

    def create(
        self,
        *,
        when: str,
        action_type: types.ActionType,
        action_config: types.ActionConfig,
        name: Optional[str] = None,
        enabled: Optional[bool] = None,
        cooldown_seconds: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> types.Rule:
        """Create a rule.

        The condition is validated against the tenant's signals, and a `webhook` action
        must reference a registered endpoint subscribed to `rule.triggered`.

        ``POST /v1/rules``
        """
        body: Dict[str, Any] = {}
        body["when"] = when
        body["action_type"] = action_type
        body["action_config"] = action_config
        if name is not None:
            body["name"] = name
        if enabled is not None:
            body["enabled"] = enabled
        if cooldown_seconds is not None:
            body["cooldown_seconds"] = cooldown_seconds
        return cast(
            "types.Rule",
            self._core.request(
                "POST",
                "/v1/rules",
                body=body,
                timeout=timeout,
            ),
        )

    def get(self, rule_id: str, *, timeout: Optional[float] = None) -> types.Rule:
        """Get a rule.

        ``GET /v1/rules/{rule_id}``
        """
        return cast(
            "types.Rule",
            self._core.request(
                "GET",
                "/v1/rules/{rule_id}",
                path_params={"rule_id": rule_id},
                timeout=timeout,
            ),
        )

    def update(
        self,
        rule_id: str,
        *,
        name: Optional[str] = None,
        when: Optional[str] = None,
        action_type: Optional[types.ActionType] = None,
        action_config: Optional[types.ActionConfig] = None,
        enabled: Optional[bool] = None,
        cooldown_seconds: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> types.Rule:
        """Update a rule.

        Omitted fields are left unchanged. The resulting condition and action are
        re-validated.

        ``PATCH /v1/rules/{rule_id}``
        """
        body: Dict[str, Any] = {}
        if name is not None:
            body["name"] = name
        if when is not None:
            body["when"] = when
        if action_type is not None:
            body["action_type"] = action_type
        if action_config is not None:
            body["action_config"] = action_config
        if enabled is not None:
            body["enabled"] = enabled
        if cooldown_seconds is not None:
            body["cooldown_seconds"] = cooldown_seconds
        return cast(
            "types.Rule",
            self._core.request(
                "PATCH",
                "/v1/rules/{rule_id}",
                path_params={"rule_id": rule_id},
                body=body,
                timeout=timeout,
            ),
        )

    def delete(self, rule_id: str, *, timeout: Optional[float] = None) -> None:
        """Delete a rule.

        ``DELETE /v1/rules/{rule_id}``
        """
        self._core.request(
            "DELETE",
            "/v1/rules/{rule_id}",
            path_params={"rule_id": rule_id},
            timeout=timeout,
        )


class RuleFiringsResource:
    """A rule fires an action (email, Slack or webhook) when an object's signal values
    cross a line you care about, such as `is_scammer >= 90`.
    """

    def __init__(self, core: Core) -> None:
        self._core = core

    def list(
        self,
        *,
        rule_id: Optional[str] = None,
        object_id: Optional[str] = None,
        limit: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> types.RuleFiringList:
        """List rule firings.

        The audit log of rule firings and their action outcomes, newest first.

        ``GET /v1/rule_firings``
        """
        return cast(
            "types.RuleFiringList",
            self._core.request(
                "GET",
                "/v1/rule_firings",
                query={"rule_id": rule_id, "object_id": object_id, "limit": limit},
                timeout=timeout,
            ),
        )


class ApiKeysResource:
    """Create, rotate and revoke the keys your integrations sign requests with."""

    def __init__(self, core: Core) -> None:
        self._core = core

    def list(self, *, timeout: Optional[float] = None) -> types.ApiKeyList:
        """List API keys.

        Revoked keys are not listed. Secrets are never returned.

        ``GET /v1/api_keys``
        """
        return cast(
            "types.ApiKeyList",
            self._core.request(
                "GET",
                "/v1/api_keys",
                timeout=timeout,
            ),
        )

    def create(
        self,
        *,
        name: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> types.ApiKeySecret:
        """Create an API key.

        Mints a key ID and signing secret. **The secret is shown only once.**

        ``POST /v1/api_keys``
        """
        body: Dict[str, Any] = {}
        if name is not None:
            body["name"] = name
        return cast(
            "types.ApiKeySecret",
            self._core.request(
                "POST",
                "/v1/api_keys",
                body=body,
                timeout=timeout,
            ),
        )

    def update(
        self,
        key_id: str,
        *,
        name: Optional[str] = None,
        status: Optional[Literal["active",
        "inactive"]] = None,
        timeout: Optional[float] = None,
    ) -> types.ApiKey:
        """Update an API key.

        Rename a key, or deactivate and reactivate it. Use `DELETE` to revoke.

        ``PATCH /v1/api_keys/{key_id}``
        """
        body: Dict[str, Any] = {}
        if name is not None:
            body["name"] = name
        if status is not None:
            body["status"] = status
        return cast(
            "types.ApiKey",
            self._core.request(
                "PATCH",
                "/v1/api_keys/{key_id}",
                path_params={"key_id": key_id},
                body=body,
                timeout=timeout,
            ),
        )

    def revoke(self, key_id: str, *, timeout: Optional[float] = None) -> None:
        """Revoke an API key.

        The key stops authenticating immediately. Its ID is never reissued.

        ``DELETE /v1/api_keys/{key_id}``
        """
        self._core.request(
            "DELETE",
            "/v1/api_keys/{key_id}",
            path_params={"key_id": key_id},
            timeout=timeout,
        )

    def rotate(self, key_id: str, *, timeout: Optional[float] = None) -> types.ApiKeySecret:
        """Rotate an API key's secret.

        Keeps the key ID and replaces the secret. The old secret stops working
        immediately; the new one is returned only once.

        ``POST /v1/api_keys/{key_id}/rotate``
        """
        return cast(
            "types.ApiKeySecret",
            self._core.request(
                "POST",
                "/v1/api_keys/{key_id}/rotate",
                path_params={"key_id": key_id},
                timeout=timeout,
            ),
        )


class BillingResource:
    """Prepaid balance, the billing ledger, and card top-ups."""

    def __init__(self, core: Core) -> None:
        self._core = core

    def get_balance(self, *, timeout: Optional[float] = None) -> types.Balance:
        """Get the prepaid balance.

        ``GET /v1/billing``
        """
        return cast(
            "types.Balance",
            self._core.request(
                "GET",
                "/v1/billing",
                timeout=timeout,
            ),
        )

    def list_ledger(
        self,
        *,
        type: Optional[Literal["credit",
        "charge"]] = None,
        limit: Optional[int] = None,
        group: Optional[Literal["batch"]] = None,
        batch_id: Optional[str] = None,
        cursor: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> types.LedgerPage:
        """List ledger entries.

        One page of the billing ledger, newest first. Pass the previous page's
        `next_cursor` as `cursor` to continue; it is empty on the last page.

        ``GET /v1/billing/ledger``
        """
        return cast(
            "types.LedgerPage",
            self._core.request(
                "GET",
                "/v1/billing/ledger",
                query={"type": type, "limit": limit, "group": group, "batch_id": batch_id, "cursor": cursor},
                timeout=timeout,
            ),
        )

    def create_checkout(
        self,
        *,
        amount_cents: int,
        timeout: Optional[float] = None,
    ) -> types.CheckoutSession:
        """Start a card top-up.

        Creates a hosted Stripe Checkout Session for the amount and returns its URL. The
        balance is credited only once Stripe confirms the payment. Returns `503` when
        card payments are not configured.

        ``POST /v1/billing/checkout``
        """
        body: Dict[str, Any] = {}
        body["amount_cents"] = amount_cents
        return cast(
            "types.CheckoutSession",
            self._core.request(
                "POST",
                "/v1/billing/checkout",
                body=body,
                timeout=timeout,
            ),
        )

    def get_checkout(
        self,
        session_id: str,
        *,
        timeout: Optional[float] = None,
    ) -> types.CheckoutStatus:
        """Get a top-up's status.

        Whether the Checkout Session's payment has been credited to the balance yet.

        ``GET /v1/billing/checkout/{session_id}``
        """
        return cast(
            "types.CheckoutStatus",
            self._core.request(
                "GET",
                "/v1/billing/checkout/{session_id}",
                path_params={"session_id": session_id},
                timeout=timeout,
            ),
        )


class UsageResource:
    """Analysis volume, spend and token usage over a date range."""

    def __init__(self, core: Core) -> None:
        self._core = core

    def get(
        self,
        *,
        from_: Optional[str] = None,
        to: Optional[str] = None,
        timeout: Optional[float] = None,
    ) -> types.Usage:
        """Get usage.

        Analyses, spend and tokens over an inclusive UTC date range (at most 366 days),
        with a zero-filled daily series and breakdowns by model, source (`async` /
        `sync`) and signal. Defaults to the last 30 days.

        ``GET /v1/usage``
        """
        return cast(
            "types.Usage",
            self._core.request(
                "GET",
                "/v1/usage",
                query={"from": from_, "to": to},
                timeout=timeout,
            ),
        )
