# Code generated by generate-sdk from api/openapi.yaml (SigWise API 1.0.0). DO NOT EDIT.
"""Types of the request and response bodies. They are plain dicts at runtime."""

from typing import Any, Dict, List, Literal, Optional, TypedDict, Union

__all__ = [
    "ApiKey",
    "ApiKeyCreate",
    "ApiKeyList",
    "ApiKeySecret",
    "ApiKeyStatus",
    "ApiKeyUpdate",
    "ActionConfig",
    "ActionType",
    "AnalysisCompletedEvent",
    "AnalyzeAllScheduled",
    "AnalyzeScheduled",
    "Answer",
    "BackfillEstimate",
    "BackfillStatus",
    "Balance",
    "CategoryCount",
    "CheckoutCreate",
    "CheckoutSession",
    "CheckoutStatus",
    "CompactedState",
    "DeliveryStatus",
    "Event",
    "EventInput",
    "EventList",
    "EventRetention",
    "EventType",
    "IngestAccepted",
    "IngestRequest",
    "LedgerBatch",
    "LedgerEntry",
    "LedgerPage",
    "Me",
    "Metadata",
    "ModerationVerdict",
    "ObjectAnalysis",
    "ObjectList",
    "ObjectState",
    "ObjectSummary",
    "Overview",
    "PlaygroundRequest",
    "PlaygroundResult",
    "RiskyObject",
    "Rule",
    "RuleCreate",
    "RuleFiring",
    "RuleFiringList",
    "RuleList",
    "RuleTriggeredEvent",
    "RuleUpdate",
    "Settings",
    "SettingsUpdate",
    "Signal",
    "SignalBackfill",
    "SignalInput",
    "SignalList",
    "SignalResult",
    "SignalSummary",
    "SignalType",
    "Usage",
    "UsageBreakdown",
    "UsageDay",
    "UsageSignal",
    "UsageTotals",
    "WebhookDelivery",
    "WebhookDeliveryList",
    "WebhookEndpoint",
    "WebhookEndpointCreate",
    "WebhookEndpointCreated",
    "WebhookEndpointList",
    "WebhookEndpointUpdate",
    "WebhookEventType",
    "WebhookEvent",
]

ApiKeyStatus = Literal["active", "inactive", "revoked"]

_ApiKeyRequired = TypedDict("_ApiKeyRequired", {
    "id": str,
    "key": str,
    "name": str,
    "status": ApiKeyStatus,
    "has_secret": bool,
    "created_at": str,
})
_ApiKeyOptional = TypedDict("_ApiKeyOptional", {
    "legacy": bool,
    "legacy_preview": str,
    "last_used_at": str,
    "legacy_used_at": str,
}, total=False)


class ApiKey(_ApiKeyRequired, _ApiKeyOptional):
    """ApiKey.

    Fields:
        key: The public key ID, sent as `api_key`.
        has_secret: Whether the key can sign requests. Legacy keys can't until
            rotated.
        legacy: Created before request signing; rotate it to get a signing secret.
    """


_ApiKeyCreateOptional = TypedDict("_ApiKeyCreateOptional", {
    "name": str,
}, total=False)


class ApiKeyCreate(_ApiKeyCreateOptional):
    """ApiKeyCreate."""


_ApiKeyListRequired = TypedDict("_ApiKeyListRequired", {
    "api_keys": List[ApiKey],
})


class ApiKeyList(_ApiKeyListRequired):
    """ApiKeyList."""


_ApiKeySecretRequired = TypedDict("_ApiKeySecretRequired", {
    "api_key": ApiKey,
    "key": str,
    "secret": str,
    "note": str,
})


class ApiKeySecret(_ApiKeySecretRequired):
    """ApiKeySecret.

    Fields:
        key: The public key ID.
        secret: The signing secret. Shown only once.
    """


_ApiKeyUpdateOptional = TypedDict("_ApiKeyUpdateOptional", {
    "name": str,
    "status": Literal["active", "inactive"],
}, total=False)


class ApiKeyUpdate(_ApiKeyUpdateOptional):
    """ApiKeyUpdate."""


# Depends on `action_type`:
#
# - `email`: `{"to": "abuse@acme.com", "subject": "…"}` (`subject` optional)
# - `slack`: `{"webhook_url": "https://hooks.slack.com/…"}`
# - `webhook`: `{"endpoint_id": "<registered endpoint id>"}`
ActionConfig = Dict[str, Any]

ActionType = Literal["email", "slack", "webhook"]

# `noul`: yes/no probability. `score`: position on a labelled spectrum. `choice`:
# one of N options.
SignalType = Literal["noul", "choice", "score"]

_AnswerRequired = TypedDict("_AnswerRequired", {
    "signal": str,
    "type": SignalType,
})
_AnswerOptional = TypedDict("_AnswerOptional", {
    "noul": float,
    "choice": str,
    "score": float,
    "probabilities": Dict[str, float],
    "confidence": float,
}, total=False)


class Answer(_AnswerRequired, _AnswerOptional):
    """One signal's answer. Only the fields for its `type` are set.

    Fields:
        type: `noul`: yes/no probability.
        noul: `noul`: the probability the answer is yes.
        choice: `choice`: the most likely option.
        score: `score`: the position on the spectrum, from 0 (the first level) to
            the number of levels minus one.
        probabilities: `choice` and `score`: the probability of each option or
            level.
        confidence: `choice` and `score`: the analyzer's confidence.
    """


_AnalysisCompletedEventRequired = TypedDict("_AnalysisCompletedEventRequired", {
    "event": Literal["analysis.completed"],
    "object_id": str,
    "tenant_id": str,
    "model": str,
    "occurred_at": str,
    "answers": List[Answer],
})


class AnalysisCompletedEvent(_AnalysisCompletedEventRequired):
    """AnalysisCompletedEvent."""


_AnalyzeAllScheduledRequired = TypedDict("_AnalyzeAllScheduledRequired", {
    "scheduled": int,
    "analysis_status": Literal["scheduled"],
})


class AnalyzeAllScheduled(_AnalyzeAllScheduledRequired):
    """AnalyzeAllScheduled.

    Fields:
        scheduled: How many objects were scheduled.
    """


_AnalyzeScheduledRequired = TypedDict("_AnalyzeScheduledRequired", {
    "object_id": str,
    "analysis_status": Literal["scheduled"],
})


class AnalyzeScheduled(_AnalyzeScheduledRequired):
    """AnalyzeScheduled."""


_BackfillEstimateRequired = TypedDict("_BackfillEstimateRequired", {
    "objects": int,
    "estimated_cost_micros": int,
})


class BackfillEstimate(_BackfillEstimateRequired):
    """BackfillEstimate.

    Fields:
        objects: Objects with no answer for the signal.
        estimated_cost_micros: Estimated cost in micro-dollars (1e-6 USD), an upper
            bound. 0 without paid history.
    """


_SignalBackfillRequired = TypedDict("_SignalBackfillRequired", {
    "signal_key": str,
    "status": Literal["running", "done"],
    "total": int,
    "completed": int,
    "pending": int,
    "started_at": str,
})


class SignalBackfill(_SignalBackfillRequired):
    """SignalBackfill.

    Fields:
        total: Objects enqueued when the backfill started.
        completed: Objects answered since it started.
        pending: Objects still queued or running.
    """


_BackfillStatusRequired = TypedDict("_BackfillStatusRequired", {
    "estimate": BackfillEstimate,
    "backfill": Optional[SignalBackfill],
})


class BackfillStatus(_BackfillStatusRequired):
    """BackfillStatus."""


_BalanceRequired = TypedDict("_BalanceRequired", {
    "balance_cents": int,
    "currency": str,
    "metering_enabled": bool,
    "enforcement": str,
    "self_serve_topup": bool,
    "low_balance_threshold_cents": int,
})
_BalanceOptional = TypedDict("_BalanceOptional", {
    "topup_min_cents": int,
    "topup_max_cents": int,
}, total=False)


class Balance(_BalanceRequired, _BalanceOptional):
    """Balance.

    Fields:
        metering_enabled: Whether analyses are billed on this deployment.
        enforcement: `block` pauses analyses at an empty balance; `grace` lets it go
            negative.
        self_serve_topup: Whether card top-ups are available.
    """


_CategoryCountRequired = TypedDict("_CategoryCountRequired", {
    "name": str,
    "count": int,
})


class CategoryCount(_CategoryCountRequired):
    """How many objects have one `object_type`."""


_CheckoutCreateRequired = TypedDict("_CheckoutCreateRequired", {
    "amount_cents": int,
})


class CheckoutCreate(_CheckoutCreateRequired):
    """CheckoutCreate.

    Fields:
        amount_cents: Within the deployment's `topup_min_cents`–`topup_max_cents`.
    """


_CheckoutSessionRequired = TypedDict("_CheckoutSessionRequired", {
    "id": str,
    "url": str,
})


class CheckoutSession(_CheckoutSessionRequired):
    """CheckoutSession.

    Fields:
        url: Send the customer here to pay.
    """


_CheckoutStatusRequired = TypedDict("_CheckoutStatusRequired", {
    "id": str,
    "status": Literal["pending", "credited"],
})
_CheckoutStatusOptional = TypedDict("_CheckoutStatusOptional", {
    "amount_cents": int,
    "balance_after_cents": int,
}, total=False)


class CheckoutStatus(_CheckoutStatusRequired, _CheckoutStatusOptional):
    """CheckoutStatus."""


_CompactedStateRequired = TypedDict("_CompactedStateRequired", {
    "total_events": int,
    "messages": int,
    "actions": int,
    "first_seen": str,
    "updated_at": str,
})
_CompactedStateOptional = TypedDict("_CompactedStateOptional", {
    "by_action": Dict[str, int],
    "sample_messages": List[str],
}, total=False)


class CompactedState(_CompactedStateRequired, _CompactedStateOptional):
    """A rolling summary of an object's older events."""


# `dead` deliveries are in the dead-letter queue: permanently rejected, or out of
# retries.
DeliveryStatus = Literal["pending", "delivering", "delivered", "dead"]

# `event` is a discrete action (e.g. `profile.updated`); `message` is free-form
# text.
EventType = Literal["event", "message"]

# Arbitrary structured attributes.
Metadata = Dict[str, Any]

_EventRequired = TypedDict("_EventRequired", {
    "type": EventType,
    "occurred_at": str,
})
_EventOptional = TypedDict("_EventOptional", {
    "name": str,
    "content": str,
    "metadata": Metadata,
}, total=False)


class Event(_EventRequired, _EventOptional):
    """Event.

    Fields:
        type: `event` is a discrete action (e.g.
        metadata: Arbitrary structured attributes.
    """


_EventInputRequired = TypedDict("_EventInputRequired", {
    "type": EventType,
})
_EventInputOptional = TypedDict("_EventInputOptional", {
    "name": str,
    "content": str,
    "metadata": Metadata,
    "occurred_at": str,
}, total=False)


class EventInput(_EventInputRequired, _EventInputOptional):
    """EventInput.

    Fields:
        type: `event` is a discrete action (e.g.
        name: The event name, or a message's subject.
        content: Free text, such as a message body.
        metadata: Arbitrary structured attributes.
        occurred_at: When it happened. Defaults to the time the API received it.
    """


_EventListRequired = TypedDict("_EventListRequired", {
    "events": List[Event],
})


class EventList(_EventListRequired):
    """EventList."""


# How long the raw events you send are kept. Answers are kept in every mode.
#
# - `forever` (default): until you delete the object.
# - `days`: deleted `event_retention_days` after they were received.
# - `after_analysis`: deleted as soon as an analysis has read them; their counts
# stay in the object's summary. Events sent with `wait: true` are never written.
# Events that cannot be analyzed are deleted after 24 hours regardless.
EventRetention = Literal["forever", "days", "after_analysis"]

_IngestAcceptedRequired = TypedDict("_IngestAcceptedRequired", {
    "object_id": str,
    "accepted": int,
    "analysis_status": Literal["scheduled"],
    "analysis_delay_ms": int,
})


class IngestAccepted(_IngestAcceptedRequired):
    """IngestAccepted.

    Fields:
        accepted: How many events were recorded.
        analysis_delay_ms: The debounce window before the analysis runs.
    """


_IngestRequestRequired = TypedDict("_IngestRequestRequired", {
    "events": List[EventInput],
})
_IngestRequestOptional = TypedDict("_IngestRequestOptional", {
    "object_type": str,
    "wait": bool,
    "signals": List[str],
    "include_history": bool,
}, total=False)


class IngestRequest(_IngestRequestRequired, _IngestRequestOptional):
    """IngestRequest.

    Fields:
        object_type: Optional classification, e.g. `user` or `listing`.
        wait: Score the object inline and return the verdict (`200`) instead of
            scheduling analysis (`202`).
        signals: With `wait`, score only these signal keys. Ignored otherwise.
        include_history: With `wait`, whether to score over the object's prior
            history (`true`) or only this request's events (`false`).
    """


_LedgerBatchRequired = TypedDict("_LedgerBatchRequired", {
    "count": int,
    "delta_micros": int,
    "input_tokens": int,
    "output_tokens": int,
    "models": int,
    "first_at": str,
})
_LedgerBatchOptional = TypedDict("_LedgerBatchOptional", {
    "model": str,
}, total=False)


class LedgerBatch(_LedgerBatchRequired, _LedgerBatchOptional):
    """The totals of a bulk run, on the entry that stands for it with `group=batch`.

    Fields:
        count: How many charges the run has.
        delta_micros: The run's total, in micro-dollars (negative).
        models: How many distinct models the run was billed for.
        model: One of the models; the only one when `models` is 1.
        first_at: When the run's first charge was made.
    """


_LedgerEntryRequired = TypedDict("_LedgerEntryRequired", {
    "id": str,
    "delta_cents": int,
    "balance_after_cents": int,
    "delta_micros": int,
    "balance_after_micros": int,
    "reason": str,
    "created_at": str,
})
_LedgerEntryOptional = TypedDict("_LedgerEntryOptional", {
    "model": str,
    "object_id": str,
    "cost_usd": float,
    "cost_margin": float,
    "input_tokens": int,
    "output_tokens": int,
    "payment_ref": str,
    "batch_id": str,
    "batch": LedgerBatch,
}, total=False)


class LedgerEntry(_LedgerEntryRequired, _LedgerEntryOptional):
    """LedgerEntry.

    Fields:
        delta_cents: Negative for a charge, positive for a credit. Sub-cent charges
            round to 0; see `delta_micros`.
        delta_micros: The exact amount in micro-dollars (1e-6 USD).
        payment_ref: The Stripe Checkout Session that paid for a top-up.
        batch_id: Shared by the charges of one bulk run (re-analyzing all objects,
            or a signal backfill). Absent for a single object's analysis and for
            credits.
        batch: The totals of a bulk run, on the entry that stands for it with
            `group=batch`.
    """


_LedgerPageRequired = TypedDict("_LedgerPageRequired", {
    "entries": List[LedgerEntry],
    "next_cursor": str,
})


class LedgerPage(_LedgerPageRequired):
    """LedgerPage.

    Fields:
        next_cursor: Pass as `cursor` for the next page. Empty on the last page.
    """


_MeRequired = TypedDict("_MeRequired", {
    "auth_type": Literal["tenant", "console"],
    "tenant_id": str,
    "tenant_name": str,
})
_MeOptional = TypedDict("_MeOptional", {
    "user_id": str,
    "email": str,
    "role": str,
    "onboarded": bool,
}, total=False)


class Me(_MeRequired, _MeOptional):
    """Me.

    Fields:
        auth_type: `tenant` for API keys, `console` for a signed-in user.
    """


_ModerationVerdictRequired = TypedDict("_ModerationVerdictRequired", {
    "object_id": str,
    "accepted": int,
    "analyzed": bool,
    "history_included": bool,
    "model": str,
    "latency_ms": int,
    "answers": List[Answer],
})
_ModerationVerdictOptional = TypedDict("_ModerationVerdictOptional", {
    "reason": str,
}, total=False)


class ModerationVerdict(_ModerationVerdictRequired, _ModerationVerdictOptional):
    """ModerationVerdict.

    Fields:
        accepted: How many events were recorded.
        analyzed: False when no configured signal matched, so nothing was scored.
        model: The model that produced the answers, e.g. `jev-1.13.0`.
        reason: Why nothing was analyzed, when `analyzed` is false.
    """


_SignalResultRequired = TypedDict("_SignalResultRequired", {
    "key": str,
    "type": SignalType,
    "computed_at": str,
})
_SignalResultOptional = TypedDict("_SignalResultOptional", {
    "noul": float,
    "choice": str,
    "score": float,
    "probabilities": Dict[str, float],
    "confidence": float,
    "model": str,
}, total=False)


class SignalResult(_SignalResultRequired, _SignalResultOptional):
    """The latest answer for one signal. Only the fields for its `type` are set.

    Fields:
        type: `noul`: yes/no probability.
    """


_ObjectAnalysisRequired = TypedDict("_ObjectAnalysisRequired", {
    "object_id": str,
    "event_count": int,
    "analysis": List[SignalResult],
    "pending": List[str],
})


class ObjectAnalysis(_ObjectAnalysisRequired):
    """ObjectAnalysis.

    Fields:
        pending: Enabled signals with no answer yet.
    """


_ObjectSummaryRequired = TypedDict("_ObjectSummaryRequired", {
    "object_id": str,
    "object_type": str,
    "event_count": int,
    "last_seen": str,
    "analysis": List[SignalResult],
    "pending": List[str],
})
_ObjectSummaryOptional = TypedDict("_ObjectSummaryOptional", {
    "display_name": str,
}, total=False)


class ObjectSummary(_ObjectSummaryRequired, _ObjectSummaryOptional):
    """ObjectSummary."""


_ObjectListRequired = TypedDict("_ObjectListRequired", {
    "objects": List[ObjectSummary],
    "limit": int,
    "offset": int,
})
_ObjectListOptional = TypedDict("_ObjectListOptional", {
    "next_cursor": str,
}, total=False)


class ObjectList(_ObjectListRequired, _ObjectListOptional):
    """ObjectList.

    Fields:
        next_cursor: Pass as `cursor` to fetch the next page. Absent on the last
            page and for signal queries.
    """


_ObjectStateRequired = TypedDict("_ObjectStateRequired", {
    "object_id": str,
    "compacted_events": int,
})
_ObjectStateOptional = TypedDict("_ObjectStateOptional", {
    "compacted_through": Optional[str],
    "compacted_state": Optional[CompactedState],
    "last_analyzed_at": Optional[str],
}, total=False)


class ObjectState(_ObjectStateRequired, _ObjectStateOptional):
    """ObjectState.

    Fields:
        compacted_events: How many events have been folded into the summary.
    """


_RiskyObjectRequired = TypedDict("_RiskyObjectRequired", {
    "object_id": str,
    "risk": float,
})
_RiskyObjectOptional = TypedDict("_RiskyObjectOptional", {
    "display_name": str,
}, total=False)


class RiskyObject(_RiskyObjectRequired, _RiskyObjectOptional):
    """One of the objects with the highest yes/no probabilities."""


_SignalSummaryRequired = TypedDict("_SignalSummaryRequired", {
    "key": str,
    "type": SignalType,
    "total": int,
})
_SignalSummaryOptional = TypedDict("_SignalSummaryOptional", {
    "avg": float,
    "high": int,
    "high_pct": float,
    "choices": Dict[str, float],
}, total=False)


class SignalSummary(_SignalSummaryRequired, _SignalSummaryOptional):
    """SignalSummary.

    Fields:
        type: `noul`: yes/no probability.
        total: Objects with an answer for the signal.
        high: Objects answered high (yes/no signals).
        choices: `choice` signals: the share of each option.
    """


_OverviewRequired = TypedDict("_OverviewRequired", {
    "objects": int,
    "signals": int,
    "analyzed_pct": float,
    "events_today": int,
    "flagged": int,
    "signal_summary": List[SignalSummary],
    "categories": List[CategoryCount],
    "top_risk": List[RiskyObject],
})


class Overview(_OverviewRequired):
    """Overview.

    Fields:
        analyzed_pct: Share of objects with at least one answer, 0–1.
        events_today: Events recorded in the last 24 hours.
    """


_PlaygroundRequestRequired = TypedDict("_PlaygroundRequestRequired", {
    "events": List[EventInput],
})
_PlaygroundRequestOptional = TypedDict("_PlaygroundRequestOptional", {
    "object_type": str,
    "signals": List[str],
}, total=False)


class PlaygroundRequest(_PlaygroundRequestRequired, _PlaygroundRequestOptional):
    """PlaygroundRequest.

    Fields:
        object_type: Optional classification, e.g. `user` or `listing`.
        signals: Score only these signal keys. Omit to score every enabled signal.
    """


_PlaygroundResultRequired = TypedDict("_PlaygroundResultRequired", {
    "analyzed": bool,
    "model": str,
    "latency_ms": int,
    "answers": List[Answer],
    "cost_micros": int,
    "events_count": int,
})
_PlaygroundResultOptional = TypedDict("_PlaygroundResultOptional", {
    "reason": str,
}, total=False)


class PlaygroundResult(_PlaygroundResultRequired, _PlaygroundResultOptional):
    """PlaygroundResult.

    Fields:
        analyzed: False when no enabled signal matched, so nothing was scored.
        model: The model that produced the answers, e.g. `jev-1.13.0`.
        cost_micros: What the run was charged, in millionths of a US dollar.
        events_count: How many events were scored.
        reason: Why nothing was analyzed, when `analyzed` is false.
    """


_RuleRequired = TypedDict("_RuleRequired", {
    "id": str,
    "name": str,
    "when": str,
    "action_type": ActionType,
    "action_config": ActionConfig,
    "enabled": bool,
    "cooldown_seconds": int,
    "created_at": str,
    "updated_at": str,
})


class Rule(_RuleRequired):
    """Rule.

    Fields:
        when: The condition, e.g. `is_scammer >= 90 and trust_score < 1`.
        action_config: Depends on `action_type`: - `email`: `{"to":
            "abuse@acme.com", "subject": "…"}` (`subject` optional) - `slack`:
            `{"webhook_url": "https://hooks.slack.com/…"}` - `webhook`:
            `{"endpoint_id": "<registered endpoint id>"}`
        cooldown_seconds: 0 fires only when the condition turns true; more lets the
            rule re-fire after that long while it stays true.
    """


_RuleCreateRequired = TypedDict("_RuleCreateRequired", {
    "when": str,
    "action_type": ActionType,
    "action_config": ActionConfig,
})
_RuleCreateOptional = TypedDict("_RuleCreateOptional", {
    "name": str,
    "enabled": bool,
    "cooldown_seconds": int,
}, total=False)


class RuleCreate(_RuleCreateRequired, _RuleCreateOptional):
    """RuleCreate.

    Fields:
        action_config: Depends on `action_type`: - `email`: `{"to":
            "abuse@acme.com", "subject": "…"}` (`subject` optional) - `slack`:
            `{"webhook_url": "https://hooks.slack.com/…"}` - `webhook`:
            `{"endpoint_id": "<registered endpoint id>"}`
    """


_RuleFiringRequired = TypedDict("_RuleFiringRequired", {
    "id": str,
    "rule_id": str,
    "object_id": str,
    "matched_when": str,
    "action_type": ActionType,
    "status": Literal["dispatched", "error"],
    "fired_at": str,
})
_RuleFiringOptional = TypedDict("_RuleFiringOptional", {
    "signal_values": Dict[str, Any],
    "detail": str,
}, total=False)


class RuleFiring(_RuleFiringRequired, _RuleFiringOptional):
    """RuleFiring.

    Fields:
        signal_values: The signal values that satisfied the condition.
        detail: The error, or a short success note.
    """


_RuleFiringListRequired = TypedDict("_RuleFiringListRequired", {
    "firings": List[RuleFiring],
})


class RuleFiringList(_RuleFiringListRequired):
    """RuleFiringList."""


_RuleListRequired = TypedDict("_RuleListRequired", {
    "rules": List[Rule],
})


class RuleList(_RuleListRequired):
    """RuleList."""


_RuleTriggeredEventRequired = TypedDict("_RuleTriggeredEventRequired", {
    "event": Literal["rule.triggered"],
    "rule_id": str,
    "tenant_id": str,
    "object_id": str,
    "matched_when": str,
    "occurred_at": str,
    "values": List[Answer],
})
_RuleTriggeredEventOptional = TypedDict("_RuleTriggeredEventOptional", {
    "rule_name": str,
    "model": str,
}, total=False)


class RuleTriggeredEvent(_RuleTriggeredEventRequired, _RuleTriggeredEventOptional):
    """RuleTriggeredEvent."""


_RuleUpdateOptional = TypedDict("_RuleUpdateOptional", {
    "name": str,
    "when": str,
    "action_type": ActionType,
    "action_config": ActionConfig,
    "enabled": bool,
    "cooldown_seconds": int,
}, total=False)


class RuleUpdate(_RuleUpdateOptional):
    """RuleUpdate.

    Fields:
        action_config: Depends on `action_type`: - `email`: `{"to":
            "abuse@acme.com", "subject": "…"}` (`subject` optional) - `slack`:
            `{"webhook_url": "https://hooks.slack.com/…"}` - `webhook`:
            `{"endpoint_id": "<registered endpoint id>"}`
    """


_SettingsRequired = TypedDict("_SettingsRequired", {
    "auto_backfill_signals": bool,
    "event_retention": EventRetention,
    "event_retention_days": Optional[int],
})


class Settings(_SettingsRequired):
    """Settings.

    Fields:
        auto_backfill_signals: Creating a signal automatically backfills existing
            objects for it. Off by default because each analysis is billed.
        event_retention: How long the raw events you send are kept.
        event_retention_days: With `event_retention` `days`, how many days events
            are kept. `null` otherwise.
    """


_SettingsUpdateOptional = TypedDict("_SettingsUpdateOptional", {
    "auto_backfill_signals": bool,
    "event_retention": EventRetention,
    "event_retention_days": int,
}, total=False)


class SettingsUpdate(_SettingsUpdateOptional):
    """SettingsUpdate.

    Fields:
        event_retention: How long the raw events you send are kept.
        event_retention_days: Required with `event_retention` `days`; not allowed
            with other values.
    """


_SignalRequired = TypedDict("_SignalRequired", {
    "key": str,
    "type": SignalType,
    "instructions": Any,
    "enabled": bool,
    "created_at": str,
    "updated_at": str,
})
_SignalOptional = TypedDict("_SignalOptional", {
    "criteria": Any,
    "backfill": SignalBackfill,
}, total=False)


class Signal(_SignalRequired, _SignalOptional):
    """Signal.

    Fields:
        type: `noul`: yes/no probability.
        backfill: Set only when creating the signal started a backfill
            (`auto_backfill_signals`).
    """


_SignalInputRequired = TypedDict("_SignalInputRequired", {
    "type": SignalType,
    "instructions": Any,
})
_SignalInputOptional = TypedDict("_SignalInputOptional", {
    "criteria": Any,
    "enabled": bool,
}, total=False)


class SignalInput(_SignalInputRequired, _SignalInputOptional):
    """SignalInput.

    Fields:
        type: `noul`: yes/no probability.
        instructions: What the analyzer should decide. Usually a string; objects and
            arrays are passed through verbatim.
        criteria: Depends on `type`; see the operation description.
    """


_SignalListRequired = TypedDict("_SignalListRequired", {
    "signals": List[Signal],
})


class SignalList(_SignalListRequired):
    """SignalList."""


_UsageBreakdownRequired = TypedDict("_UsageBreakdownRequired", {
    "key": str,
    "analyses": int,
    "spend_micros": int,
    "input_tokens": int,
    "output_tokens": int,
})


class UsageBreakdown(_UsageBreakdownRequired):
    """UsageBreakdown."""


_UsageDayRequired = TypedDict("_UsageDayRequired", {
    "date": str,
    "analyses": int,
    "async": int,
    "sync": int,
    "spend_micros": int,
})


class UsageDay(_UsageDayRequired):
    """UsageDay."""


_UsageSignalRequired = TypedDict("_UsageSignalRequired", {
    "signal": str,
    "analyses": int,
})


class UsageSignal(_UsageSignalRequired):
    """UsageSignal."""


_UsageTotalsRequired = TypedDict("_UsageTotalsRequired", {
    "analyses": int,
    "spend_micros": int,
    "input_tokens": int,
    "output_tokens": int,
})


class UsageTotals(_UsageTotalsRequired):
    """UsageTotals."""


_UsageRequired = TypedDict("_UsageRequired", {
    "from": str,
    "to": str,
    "currency": str,
    "metering_enabled": bool,
    "balance_cents": int,
    "burn_rate_micros_per_day": int,
    "totals": UsageTotals,
    "series": List[UsageDay],
    "by_model": List[UsageBreakdown],
    "by_source": List[UsageBreakdown],
    "by_signal": List[UsageSignal],
})
_UsageOptional = TypedDict("_UsageOptional", {
    "runway_days": float,
}, total=False)


class Usage(_UsageRequired, _UsageOptional):
    """Usage.

    Fields:
        burn_rate_micros_per_day: Average spend per elapsed day of the range, in
            micro-dollars.
        runway_days: Balance divided by burn rate. Omitted without spend or balance.
    """


_WebhookDeliveryRequired = TypedDict("_WebhookDeliveryRequired", {
    "id": str,
    "endpoint_id": str,
    "event_type": Literal["analysis.completed", "rule.triggered"],
    "status": DeliveryStatus,
    "attempts": int,
    "max_attempts": int,
    "run_after": str,
    "created_at": str,
})
_WebhookDeliveryOptional = TypedDict("_WebhookDeliveryOptional", {
    "object_id": str,
    "last_status_code": int,
    "last_error": str,
    "delivered_at": str,
    "payload": Dict[str, Any],
}, total=False)


class WebhookDelivery(_WebhookDeliveryRequired, _WebhookDeliveryOptional):
    """WebhookDelivery.

    Fields:
        status: `dead` deliveries are in the dead-letter queue: permanently
            rejected, or out of retries.
        last_status_code: The endpoint's last HTTP status, if it answered.
        run_after: When the next attempt is due.
        payload: The body that is (or was) delivered.
    """


_WebhookDeliveryListRequired = TypedDict("_WebhookDeliveryListRequired", {
    "deliveries": List[WebhookDelivery],
})


class WebhookDeliveryList(_WebhookDeliveryListRequired):
    """WebhookDeliveryList."""


WebhookEventType = Literal["analysis.completed", "rule.triggered"]

_WebhookEndpointRequired = TypedDict("_WebhookEndpointRequired", {
    "id": str,
    "url": str,
    "description": str,
    "enabled": bool,
    "signal_keys": List[str],
    "events": List[WebhookEventType],
    "created_at": str,
    "updated_at": str,
})


class WebhookEndpoint(_WebhookEndpointRequired):
    """WebhookEndpoint.

    Fields:
        signal_keys: Only deliver analyses that answered one of these signals. Empty
            means every analysis.
        events: The event types this endpoint receives.
    """


_WebhookEndpointCreateRequired = TypedDict("_WebhookEndpointCreateRequired", {
    "url": str,
})
_WebhookEndpointCreateOptional = TypedDict("_WebhookEndpointCreateOptional", {
    "description": str,
    "signal_keys": List[str],
    "events": List[WebhookEventType],
    "enabled": bool,
}, total=False)


class WebhookEndpointCreate(_WebhookEndpointCreateRequired, _WebhookEndpointCreateOptional):
    """WebhookEndpointCreate.

    Fields:
        url: An `http` or `https` URL.
        events: The event types to deliver. Omit to receive every event type. Use
            `["rule.triggered"]` for an endpoint that only receives rule firings.
    """


_WebhookEndpointCreatedRequired = TypedDict("_WebhookEndpointCreatedRequired", {
    "endpoint": WebhookEndpoint,
    "secret": str,
    "note": str,
})


class WebhookEndpointCreated(_WebhookEndpointCreatedRequired):
    """WebhookEndpointCreated.

    Fields:
        secret: The signing secret. Shown only once.
    """


_WebhookEndpointListRequired = TypedDict("_WebhookEndpointListRequired", {
    "webhooks": List[WebhookEndpoint],
})


class WebhookEndpointList(_WebhookEndpointListRequired):
    """WebhookEndpointList."""


_WebhookEndpointUpdateOptional = TypedDict("_WebhookEndpointUpdateOptional", {
    "url": str,
    "description": str,
    "signal_keys": List[str],
    "events": List[WebhookEventType],
    "enabled": bool,
}, total=False)


class WebhookEndpointUpdate(_WebhookEndpointUpdateOptional):
    """WebhookEndpointUpdate."""


# A webhook delivery's body. Check its "event" key to tell them apart.
WebhookEvent = Union[AnalysisCompletedEvent, RuleTriggeredEvent]
